In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)
print()
b = np.array([(1.5,2,3.3), (4,5,6)], dtype = float)
print(b)
print(b.ndim)
print(b.size)
print(b.dtype)
print(b.dtype.name)
tc=b.astype(int)
print(tc)
print(tc.dtype)
print()
c = np.array([(1.5,2,3), (4,5,6),(3,2,1), (4,5,6)], dtype = float)
c.shape
l=len(c)
print(c)
print(l)
print()
z=np.zeros((4,4))
print(z)
print()
o=np.ones((2,4),dtype=np.int16)
print(o)
print()
e = np.full((2,2),18)
print(e)
print()
f = np.eye(4)
print(f)
print()
r=np.random.random((2,2))
print(r)
print()
e=np.empty((3,2))
print(e) 
print() 
np.info(np.ndarray.dtype)
# np.int64 
# np.float32 
# np.complex 
# np.bool 
# np.object 
# np.string_ 
# np.unicode_
np.subtract(a,b)
np.add(a,b)
np.multiply(a,b)
np.divide(a,b)
np.exp(a)
np.sqrt(a)
np.sin(a)
np.cos(a)
np.log(a)
a.dot(a)
k=(a<=2)
print(k)

[1 2 3]

[[1.5 2.  3.3]
 [4.  5.  6. ]]
2
6
float64
float64
[[1 2 3]
 [4 5 6]]
int32

[[1.5 2.  3. ]
 [4.  5.  6. ]
 [3.  2.  1. ]
 [4.  5.  6. ]]
4

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1 1 1 1]
 [1 1 1 1]]

[[18 18]
 [18 18]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[0.32958787 0.65753114]
 [0.3679388  0.34957615]]

[[1.5 2. ]
 [3.3 4. ]
 [5.  6. ]]

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>
[ True  True False]
